version: "3.9"
x-airflow-environment: &airflow-environment
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
  AIRFLOW__DAG_DEFAULT_VIEW: graph

services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: airflow
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  webserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    command: ["airflow", "webserver"]
    restart: always

  scheduler:
    build: .
    environment:
      <<: *airflow-environment
    depends_on:
      - postgres
    command: ["airflow", "scheduler"]
    restart: always
